/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#ifdef _MSC_VER
#pragma optimize("", off)
#elif defined(__clang__)
#pragma clang optimize off
#elif defined(__GNUC__)
#pragma GCC optimize ("O0")
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 21
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 18
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_01 = 1,
  aux_sym_starting_record_token1 = 2,
  sym_layout_name = 3,
  sym_layout_version = 4,
  sym_creation_timestamp = 5,
  anon_sym_T = 6,
  anon_sym_P = 7,
  anon_sym_70 = 8,
  aux_sym_end_record_token1 = 9,
  sym_number_of = 10,
  sym_catch_all = 11,
  sym_source_file = 12,
  sym_starting_record = 13,
  sym_test_indicator = 14,
  sym_end_record = 15,
  sym_catch_all_lines = 16,
  aux_sym_catch_all_lines_repeat1 = 17,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_01] = "01",
  [aux_sym_starting_record_token1] = "starting_record_token1",
  [sym_layout_name] = "layout_name",
  [sym_layout_version] = "layout_version",
  [sym_creation_timestamp] = "creation_timestamp",
  [anon_sym_T] = "T",
  [anon_sym_P] = "P",
  [anon_sym_70] = "70",
  [aux_sym_end_record_token1] = "end_record_token1",
  [sym_number_of] = "number_of",
  [sym_catch_all] = "catch_all",
  [sym_source_file] = "source_file",
  [sym_starting_record] = "starting_record",
  [sym_test_indicator] = "test_indicator",
  [sym_end_record] = "end_record",
  [sym_catch_all_lines] = "catch_all_lines",
  [aux_sym_catch_all_lines_repeat1] = "catch_all_lines_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_01] = anon_sym_01,
  [aux_sym_starting_record_token1] = aux_sym_starting_record_token1,
  [sym_layout_name] = sym_layout_name,
  [sym_layout_version] = sym_layout_version,
  [sym_creation_timestamp] = sym_creation_timestamp,
  [anon_sym_T] = anon_sym_T,
  [anon_sym_P] = anon_sym_P,
  [anon_sym_70] = anon_sym_70,
  [aux_sym_end_record_token1] = aux_sym_end_record_token1,
  [sym_number_of] = sym_number_of,
  [sym_catch_all] = sym_catch_all,
  [sym_source_file] = sym_source_file,
  [sym_starting_record] = sym_starting_record,
  [sym_test_indicator] = sym_test_indicator,
  [sym_end_record] = sym_end_record,
  [sym_catch_all_lines] = sym_catch_all_lines,
  [aux_sym_catch_all_lines_repeat1] = aux_sym_catch_all_lines_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_01] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_starting_record_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_layout_name] = {
    .visible = true,
    .named = true,
  },
  [sym_layout_version] = {
    .visible = true,
    .named = true,
  },
  [sym_creation_timestamp] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_T] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_P] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_70] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_end_record_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_number_of] = {
    .visible = true,
    .named = true,
  },
  [sym_catch_all] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_starting_record] = {
    .visible = true,
    .named = true,
  },
  [sym_test_indicator] = {
    .visible = true,
    .named = true,
  },
  [sym_end_record] = {
    .visible = true,
    .named = true,
  },
  [sym_catch_all_lines] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_catch_all_lines_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_number_of_deduction_records = 1,
  field_number_of_deposit_records = 2,
  field_number_of_extra_reference_records = 3,
  field_number_of_payment_records = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_number_of_deduction_records] = "number_of_deduction_records",
  [field_number_of_deposit_records] = "number_of_deposit_records",
  [field_number_of_extra_reference_records] = "number_of_extra_reference_records",
  [field_number_of_payment_records] = "number_of_payment_records",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_number_of_deduction_records, 2},
    {field_number_of_deposit_records, 4},
    {field_number_of_extra_reference_records, 3},
    {field_number_of_payment_records, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(328);
      if (lookahead == '0') ADVANCE(105);
      if (lookahead == '1') ADVANCE(106);
      if (lookahead == '2') ADVANCE(109);
      if (lookahead == '7') ADVANCE(104);
      if (lookahead == 'P') ADVANCE(357);
      if (lookahead == 'T') ADVANCE(356);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(353);
      if (lookahead != 0) ADVANCE(354);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(332);
      if (lookahead != 0) ADVANCE(351);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(3);
      if (lookahead != 0) ADVANCE(326);
      END_STATE();
    case 5:
      if (lookahead == '\n') SKIP(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(6);
      if (lookahead != 0) ADVANCE(318);
      END_STATE();
    case 6:
      if (lookahead == '\n') SKIP(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead != 0) ADVANCE(323);
      END_STATE();
    case 7:
      if (lookahead == '\n') SKIP(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(5);
      if (lookahead != 0) ADVANCE(311);
      END_STATE();
    case 8:
      if (lookahead == '\n') SKIP(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead != 0) ADVANCE(302);
      END_STATE();
    case 9:
      if (lookahead == '\n') SKIP(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(8);
      if (lookahead != 0) ADVANCE(291);
      END_STATE();
    case 10:
      if (lookahead == '\n') SKIP(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead != 0) ADVANCE(278);
      END_STATE();
    case 11:
      if (lookahead == '\n') SKIP(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(10);
      if (lookahead != 0) ADVANCE(263);
      END_STATE();
    case 12:
      if (lookahead == '\n') SKIP(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0) ADVANCE(246);
      END_STATE();
    case 13:
      if (lookahead == '\n') SKIP(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0) ADVANCE(228);
      END_STATE();
    case 14:
      if (lookahead == '\n') SKIP(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0) ADVANCE(247);
      END_STATE();
    case 15:
      if (lookahead == '\n') SKIP(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0) ADVANCE(264);
      END_STATE();
    case 16:
      if (lookahead == '\n') SKIP(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0) ADVANCE(279);
      END_STATE();
    case 17:
      if (lookahead == '\n') SKIP(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0) ADVANCE(292);
      END_STATE();
    case 18:
      if (lookahead == '\n') SKIP(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0) ADVANCE(303);
      END_STATE();
    case 19:
      if (lookahead == '\n') SKIP(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0) ADVANCE(312);
      END_STATE();
    case 20:
      if (lookahead == '\n') SKIP(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0) ADVANCE(319);
      END_STATE();
    case 21:
      if (lookahead == '\n') SKIP(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0) ADVANCE(324);
      END_STATE();
    case 22:
      if (lookahead == '\n') SKIP(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0) ADVANCE(327);
      END_STATE();
    case 23:
      if (lookahead == ' ') ADVANCE(330);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 24:
      if (lookahead == ' ') ADVANCE(359);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 25:
      if (lookahead == ' ') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 26:
      if (lookahead == ' ') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 27:
      if (lookahead == ' ') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 28:
      if (lookahead == ' ') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 29:
      if (lookahead == ' ') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 30:
      if (lookahead == ' ') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 31:
      if (lookahead == ' ') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 32:
      if (lookahead == ' ') ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 33:
      if (lookahead == ' ') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 34:
      if (lookahead == ' ') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 35:
      if (lookahead == ' ') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 36:
      if (lookahead == ' ') ADVANCE(34);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 37:
      if (lookahead == ' ') ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 38:
      if (lookahead == ' ') ADVANCE(36);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 39:
      if (lookahead == ' ') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 40:
      if (lookahead == ' ') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 41:
      if (lookahead == ' ') ADVANCE(39);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 42:
      if (lookahead == ' ') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 43:
      if (lookahead == ' ') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 44:
      if (lookahead == ' ') ADVANCE(42);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 45:
      if (lookahead == ' ') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 46:
      if (lookahead == ' ') ADVANCE(44);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 47:
      if (lookahead == ' ') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 48:
      if (lookahead == ' ') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 49:
      if (lookahead == ' ') ADVANCE(47);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 50:
      if (lookahead == ' ') ADVANCE(48);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 51:
      if (lookahead == ' ') ADVANCE(49);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 52:
      if (lookahead == ' ') ADVANCE(50);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 53:
      if (lookahead == ' ') ADVANCE(51);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 54:
      if (lookahead == ' ') ADVANCE(52);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 55:
      if (lookahead == ' ') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 56:
      if (lookahead == ' ') ADVANCE(54);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 57:
      if (lookahead == ' ') ADVANCE(55);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 58:
      if (lookahead == ' ') ADVANCE(56);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 59:
      if (lookahead == ' ') ADVANCE(57);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 60:
      if (lookahead == ' ') ADVANCE(58);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 61:
      if (lookahead == ' ') ADVANCE(59);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 62:
      if (lookahead == ' ') ADVANCE(60);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 63:
      if (lookahead == ' ') ADVANCE(61);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 64:
      if (lookahead == ' ') ADVANCE(62);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 65:
      if (lookahead == ' ') ADVANCE(63);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 66:
      if (lookahead == ' ') ADVANCE(64);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 67:
      if (lookahead == ' ') ADVANCE(65);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 68:
      if (lookahead == ' ') ADVANCE(66);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 69:
      if (lookahead == ' ') ADVANCE(67);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 70:
      if (lookahead == ' ') ADVANCE(68);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 71:
      if (lookahead == ' ') ADVANCE(69);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 72:
      if (lookahead == ' ') ADVANCE(70);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 73:
      if (lookahead == ' ') ADVANCE(71);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 74:
      if (lookahead == ' ') ADVANCE(72);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 75:
      if (lookahead == ' ') ADVANCE(73);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 76:
      if (lookahead == ' ') ADVANCE(74);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 77:
      if (lookahead == ' ') ADVANCE(75);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 78:
      if (lookahead == ' ') ADVANCE(76);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 79:
      if (lookahead == ' ') ADVANCE(77);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 80:
      if (lookahead == ' ') ADVANCE(78);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 81:
      if (lookahead == ' ') ADVANCE(79);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 82:
      if (lookahead == ' ') ADVANCE(80);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 83:
      if (lookahead == ' ') ADVANCE(81);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 84:
      if (lookahead == ' ') ADVANCE(82);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 85:
      if (lookahead == ' ') ADVANCE(83);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 86:
      if (lookahead == ' ') ADVANCE(84);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 87:
      if (lookahead == ' ') ADVANCE(85);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 88:
      if (lookahead == ' ') ADVANCE(86);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 89:
      if (lookahead == ' ') ADVANCE(87);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 90:
      if (lookahead == ' ') ADVANCE(88);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 91:
      if (lookahead == ' ') ADVANCE(89);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(91);
      END_STATE();
    case 92:
      if (lookahead == ' ') ADVANCE(90);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 93:
      if (lookahead == ' ') ADVANCE(92);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 94:
      if (lookahead == ' ') ADVANCE(93);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 95:
      if (lookahead == ' ') ADVANCE(94);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 96:
      if (lookahead == ' ') ADVANCE(95);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 97:
      if (lookahead == ' ') ADVANCE(96);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 98:
      if (lookahead == ' ') ADVANCE(97);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 99:
      if (lookahead == ' ') ADVANCE(98);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 100:
      if (lookahead == ' ') ADVANCE(99);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 101:
      if (lookahead == ' ') ADVANCE(100);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 102:
      if (lookahead == ' ') ADVANCE(101);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 103:
      if (lookahead == ' ') ADVANCE(102);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(103);
      END_STATE();
    case 104:
      if (lookahead == '0') ADVANCE(358);
      END_STATE();
    case 105:
      if (lookahead == '1') ADVANCE(329);
      if (lookahead == '5') ADVANCE(136);
      END_STATE();
    case 106:
      if (lookahead == '5') ADVANCE(136);
      END_STATE();
    case 107:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(107);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(135);
      END_STATE();
    case 108:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(108);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(123);
      END_STATE();
    case 109:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(136);
      END_STATE();
    case 110:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(355);
      END_STATE();
    case 111:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(360);
      END_STATE();
    case 112:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(110);
      END_STATE();
    case 113:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(111);
      END_STATE();
    case 114:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(112);
      END_STATE();
    case 115:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(113);
      END_STATE();
    case 116:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(114);
      END_STATE();
    case 117:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(115);
      END_STATE();
    case 118:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(116);
      END_STATE();
    case 119:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(117);
      END_STATE();
    case 120:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(118);
      END_STATE();
    case 121:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(119);
      END_STATE();
    case 122:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(120);
      END_STATE();
    case 123:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(121);
      END_STATE();
    case 124:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(122);
      END_STATE();
    case 125:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(124);
      END_STATE();
    case 126:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(125);
      END_STATE();
    case 127:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(126);
      END_STATE();
    case 128:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(127);
      END_STATE();
    case 129:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(128);
      END_STATE();
    case 130:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(129);
      END_STATE();
    case 131:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(130);
      END_STATE();
    case 132:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(131);
      END_STATE();
    case 133:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(132);
      END_STATE();
    case 134:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(133);
      END_STATE();
    case 135:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(134);
      END_STATE();
    case 136:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(361);
      END_STATE();
    case 137:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(352);
      END_STATE();
    case 138:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(331);
      END_STATE();
    case 139:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(333);
      END_STATE();
    case 140:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(139);
      END_STATE();
    case 141:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(138);
      END_STATE();
    case 142:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(334);
      END_STATE();
    case 143:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(142);
      END_STATE();
    case 144:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(143);
      END_STATE();
    case 145:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(140);
      END_STATE();
    case 146:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(141);
      END_STATE();
    case 147:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(335);
      END_STATE();
    case 148:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(147);
      END_STATE();
    case 149:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(148);
      END_STATE();
    case 150:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(149);
      END_STATE();
    case 151:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(144);
      END_STATE();
    case 152:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(145);
      END_STATE();
    case 153:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 154:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(336);
      END_STATE();
    case 155:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(154);
      END_STATE();
    case 156:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(155);
      END_STATE();
    case 157:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(156);
      END_STATE();
    case 158:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(157);
      END_STATE();
    case 159:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(150);
      END_STATE();
    case 160:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(151);
      END_STATE();
    case 161:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(152);
      END_STATE();
    case 162:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(153);
      END_STATE();
    case 163:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(337);
      END_STATE();
    case 164:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(163);
      END_STATE();
    case 165:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(164);
      END_STATE();
    case 166:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(165);
      END_STATE();
    case 167:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(166);
      END_STATE();
    case 168:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(167);
      END_STATE();
    case 169:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(158);
      END_STATE();
    case 170:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(159);
      END_STATE();
    case 171:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(160);
      END_STATE();
    case 172:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(161);
      END_STATE();
    case 173:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(162);
      END_STATE();
    case 174:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(338);
      END_STATE();
    case 175:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(174);
      END_STATE();
    case 176:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(175);
      END_STATE();
    case 177:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(176);
      END_STATE();
    case 178:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(177);
      END_STATE();
    case 179:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(178);
      END_STATE();
    case 180:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(179);
      END_STATE();
    case 181:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(168);
      END_STATE();
    case 182:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 183:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(170);
      END_STATE();
    case 184:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(171);
      END_STATE();
    case 185:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(172);
      END_STATE();
    case 186:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(173);
      END_STATE();
    case 187:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(339);
      END_STATE();
    case 188:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(187);
      END_STATE();
    case 189:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(188);
      END_STATE();
    case 190:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(189);
      END_STATE();
    case 191:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(190);
      END_STATE();
    case 192:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(191);
      END_STATE();
    case 193:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 194:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(193);
      END_STATE();
    case 195:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(180);
      END_STATE();
    case 196:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(181);
      END_STATE();
    case 197:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(182);
      END_STATE();
    case 198:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(183);
      END_STATE();
    case 199:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(184);
      END_STATE();
    case 200:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(185);
      END_STATE();
    case 201:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(186);
      END_STATE();
    case 202:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(340);
      END_STATE();
    case 203:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(202);
      END_STATE();
    case 204:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(203);
      END_STATE();
    case 205:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(204);
      END_STATE();
    case 206:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(205);
      END_STATE();
    case 207:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(206);
      END_STATE();
    case 208:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(207);
      END_STATE();
    case 209:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 210:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(209);
      END_STATE();
    case 211:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(194);
      END_STATE();
    case 212:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 213:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(196);
      END_STATE();
    case 214:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(197);
      END_STATE();
    case 215:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(198);
      END_STATE();
    case 216:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(199);
      END_STATE();
    case 217:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(200);
      END_STATE();
    case 218:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(201);
      END_STATE();
    case 219:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(341);
      END_STATE();
    case 220:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(219);
      END_STATE();
    case 221:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(220);
      END_STATE();
    case 222:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(221);
      END_STATE();
    case 223:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(222);
      END_STATE();
    case 224:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(223);
      END_STATE();
    case 225:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(224);
      END_STATE();
    case 226:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(225);
      END_STATE();
    case 227:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(226);
      END_STATE();
    case 228:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(227);
      END_STATE();
    case 229:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 230:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(211);
      END_STATE();
    case 231:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(212);
      END_STATE();
    case 232:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(213);
      END_STATE();
    case 233:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(214);
      END_STATE();
    case 234:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(215);
      END_STATE();
    case 235:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(216);
      END_STATE();
    case 236:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(217);
      END_STATE();
    case 237:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(218);
      END_STATE();
    case 238:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(342);
      END_STATE();
    case 239:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(238);
      END_STATE();
    case 240:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(239);
      END_STATE();
    case 241:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(240);
      END_STATE();
    case 242:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(241);
      END_STATE();
    case 243:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(242);
      END_STATE();
    case 244:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(243);
      END_STATE();
    case 245:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(244);
      END_STATE();
    case 246:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(245);
      END_STATE();
    case 247:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(229);
      END_STATE();
    case 248:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(230);
      END_STATE();
    case 249:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(231);
      END_STATE();
    case 250:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(232);
      END_STATE();
    case 251:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(233);
      END_STATE();
    case 252:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(234);
      END_STATE();
    case 253:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(235);
      END_STATE();
    case 254:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(236);
      END_STATE();
    case 255:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(237);
      END_STATE();
    case 256:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(343);
      END_STATE();
    case 257:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(256);
      END_STATE();
    case 258:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(257);
      END_STATE();
    case 259:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(258);
      END_STATE();
    case 260:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(259);
      END_STATE();
    case 261:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(260);
      END_STATE();
    case 262:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(261);
      END_STATE();
    case 263:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(262);
      END_STATE();
    case 264:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(248);
      END_STATE();
    case 265:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(249);
      END_STATE();
    case 266:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(250);
      END_STATE();
    case 267:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(251);
      END_STATE();
    case 268:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(252);
      END_STATE();
    case 269:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(253);
      END_STATE();
    case 270:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(254);
      END_STATE();
    case 271:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(255);
      END_STATE();
    case 272:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(344);
      END_STATE();
    case 273:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(272);
      END_STATE();
    case 274:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(273);
      END_STATE();
    case 275:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(274);
      END_STATE();
    case 276:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(275);
      END_STATE();
    case 277:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(276);
      END_STATE();
    case 278:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(277);
      END_STATE();
    case 279:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(265);
      END_STATE();
    case 280:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(266);
      END_STATE();
    case 281:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(267);
      END_STATE();
    case 282:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(268);
      END_STATE();
    case 283:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(269);
      END_STATE();
    case 284:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(270);
      END_STATE();
    case 285:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(271);
      END_STATE();
    case 286:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(345);
      END_STATE();
    case 287:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(286);
      END_STATE();
    case 288:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(287);
      END_STATE();
    case 289:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(288);
      END_STATE();
    case 290:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(289);
      END_STATE();
    case 291:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(290);
      END_STATE();
    case 292:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(280);
      END_STATE();
    case 293:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(281);
      END_STATE();
    case 294:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(282);
      END_STATE();
    case 295:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(283);
      END_STATE();
    case 296:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(284);
      END_STATE();
    case 297:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(285);
      END_STATE();
    case 298:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(346);
      END_STATE();
    case 299:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 300:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(299);
      END_STATE();
    case 301:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(300);
      END_STATE();
    case 302:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(301);
      END_STATE();
    case 303:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(293);
      END_STATE();
    case 304:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(294);
      END_STATE();
    case 305:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(295);
      END_STATE();
    case 306:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(296);
      END_STATE();
    case 307:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(297);
      END_STATE();
    case 308:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(347);
      END_STATE();
    case 309:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(308);
      END_STATE();
    case 310:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(309);
      END_STATE();
    case 311:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(310);
      END_STATE();
    case 312:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(304);
      END_STATE();
    case 313:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(305);
      END_STATE();
    case 314:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(306);
      END_STATE();
    case 315:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(307);
      END_STATE();
    case 316:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(348);
      END_STATE();
    case 317:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(316);
      END_STATE();
    case 318:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(317);
      END_STATE();
    case 319:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(313);
      END_STATE();
    case 320:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(314);
      END_STATE();
    case 321:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(315);
      END_STATE();
    case 322:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(349);
      END_STATE();
    case 323:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(322);
      END_STATE();
    case 324:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(320);
      END_STATE();
    case 325:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(321);
      END_STATE();
    case 326:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(350);
      END_STATE();
    case 327:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(325);
      END_STATE();
    case 328:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 329:
      ACCEPT_TOKEN(anon_sym_01);
      END_STATE();
    case 330:
      ACCEPT_TOKEN(aux_sym_starting_record_token1);
      if (lookahead == ' ') ADVANCE(330);
      END_STATE();
    case 331:
      ACCEPT_TOKEN(sym_layout_name);
      END_STATE();
    case 332:
      ACCEPT_TOKEN(sym_layout_name);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(332);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(351);
      END_STATE();
    case 333:
      ACCEPT_TOKEN(sym_layout_name);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(331);
      END_STATE();
    case 334:
      ACCEPT_TOKEN(sym_layout_name);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(333);
      END_STATE();
    case 335:
      ACCEPT_TOKEN(sym_layout_name);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(334);
      END_STATE();
    case 336:
      ACCEPT_TOKEN(sym_layout_name);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(335);
      END_STATE();
    case 337:
      ACCEPT_TOKEN(sym_layout_name);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(336);
      END_STATE();
    case 338:
      ACCEPT_TOKEN(sym_layout_name);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(337);
      END_STATE();
    case 339:
      ACCEPT_TOKEN(sym_layout_name);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(338);
      END_STATE();
    case 340:
      ACCEPT_TOKEN(sym_layout_name);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(339);
      END_STATE();
    case 341:
      ACCEPT_TOKEN(sym_layout_name);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(340);
      END_STATE();
    case 342:
      ACCEPT_TOKEN(sym_layout_name);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(341);
      END_STATE();
    case 343:
      ACCEPT_TOKEN(sym_layout_name);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(342);
      END_STATE();
    case 344:
      ACCEPT_TOKEN(sym_layout_name);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(343);
      END_STATE();
    case 345:
      ACCEPT_TOKEN(sym_layout_name);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(344);
      END_STATE();
    case 346:
      ACCEPT_TOKEN(sym_layout_name);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(345);
      END_STATE();
    case 347:
      ACCEPT_TOKEN(sym_layout_name);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(346);
      END_STATE();
    case 348:
      ACCEPT_TOKEN(sym_layout_name);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(347);
      END_STATE();
    case 349:
      ACCEPT_TOKEN(sym_layout_name);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(348);
      END_STATE();
    case 350:
      ACCEPT_TOKEN(sym_layout_name);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(349);
      END_STATE();
    case 351:
      ACCEPT_TOKEN(sym_layout_name);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(350);
      END_STATE();
    case 352:
      ACCEPT_TOKEN(sym_layout_version);
      END_STATE();
    case 353:
      ACCEPT_TOKEN(sym_layout_version);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(353);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(354);
      END_STATE();
    case 354:
      ACCEPT_TOKEN(sym_layout_version);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(352);
      END_STATE();
    case 355:
      ACCEPT_TOKEN(sym_creation_timestamp);
      END_STATE();
    case 356:
      ACCEPT_TOKEN(anon_sym_T);
      END_STATE();
    case 357:
      ACCEPT_TOKEN(anon_sym_P);
      END_STATE();
    case 358:
      ACCEPT_TOKEN(anon_sym_70);
      END_STATE();
    case 359:
      ACCEPT_TOKEN(aux_sym_end_record_token1);
      if (lookahead == ' ') ADVANCE(359);
      END_STATE();
    case 360:
      ACCEPT_TOKEN(sym_number_of);
      END_STATE();
    case 361:
      ACCEPT_TOKEN(sym_catch_all);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(361);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 22},
  [10] = {.lex_state = 107},
  [11] = {.lex_state = 108},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 108},
  [14] = {.lex_state = 91},
  [15] = {.lex_state = 91},
  [16] = {.lex_state = 108},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 108},
  [19] = {.lex_state = 103},
  [20] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_01] = ACTIONS(1),
    [anon_sym_T] = ACTIONS(1),
    [anon_sym_P] = ACTIONS(1),
    [anon_sym_70] = ACTIONS(1),
    [sym_catch_all] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(7),
    [sym_starting_record] = STATE(2),
    [anon_sym_01] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(5), 1,
      sym_catch_all,
    STATE(3), 1,
      aux_sym_catch_all_lines_repeat1,
    STATE(6), 1,
      sym_catch_all_lines,
  [10] = 3,
    ACTIONS(7), 1,
      anon_sym_70,
    ACTIONS(9), 1,
      sym_catch_all,
    STATE(5), 1,
      aux_sym_catch_all_lines_repeat1,
  [20] = 2,
    STATE(15), 1,
      sym_test_indicator,
    ACTIONS(11), 2,
      anon_sym_T,
      anon_sym_P,
  [28] = 3,
    ACTIONS(13), 1,
      anon_sym_70,
    ACTIONS(15), 1,
      sym_catch_all,
    STATE(5), 1,
      aux_sym_catch_all_lines_repeat1,
  [38] = 2,
    ACTIONS(18), 1,
      anon_sym_70,
    STATE(12), 1,
      sym_end_record,
  [45] = 1,
    ACTIONS(20), 1,
      ts_builtin_sym_end,
  [49] = 1,
    ACTIONS(22), 1,
      sym_layout_version,
  [53] = 1,
    ACTIONS(24), 1,
      sym_layout_name,
  [57] = 1,
    ACTIONS(26), 1,
      sym_creation_timestamp,
  [61] = 1,
    ACTIONS(28), 1,
      sym_number_of,
  [65] = 1,
    ACTIONS(30), 1,
      ts_builtin_sym_end,
  [69] = 1,
    ACTIONS(32), 1,
      sym_number_of,
  [73] = 1,
    ACTIONS(34), 1,
      aux_sym_starting_record_token1,
  [77] = 1,
    ACTIONS(36), 1,
      aux_sym_starting_record_token1,
  [81] = 1,
    ACTIONS(38), 1,
      sym_number_of,
  [85] = 1,
    ACTIONS(40), 1,
      sym_catch_all,
  [89] = 1,
    ACTIONS(42), 1,
      sym_number_of,
  [93] = 1,
    ACTIONS(44), 1,
      aux_sym_end_record_token1,
  [97] = 1,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 10,
  [SMALL_STATE(4)] = 20,
  [SMALL_STATE(5)] = 28,
  [SMALL_STATE(6)] = 38,
  [SMALL_STATE(7)] = 45,
  [SMALL_STATE(8)] = 49,
  [SMALL_STATE(9)] = 53,
  [SMALL_STATE(10)] = 57,
  [SMALL_STATE(11)] = 61,
  [SMALL_STATE(12)] = 65,
  [SMALL_STATE(13)] = 69,
  [SMALL_STATE(14)] = 73,
  [SMALL_STATE(15)] = 77,
  [SMALL_STATE(16)] = 81,
  [SMALL_STATE(17)] = 85,
  [SMALL_STATE(18)] = 89,
  [SMALL_STATE(19)] = 93,
  [SMALL_STATE(20)] = 97,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_catch_all_lines, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_catch_all_lines_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_catch_all_lines_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [18] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [20] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [22] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [24] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_test_indicator, 1, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_starting_record, 6, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_record, 6, 0, 1),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_bgmax(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "bgmax",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
